### ISSUE TITLE
@autoclosure in Swift 5

### ISSUE THREAD

**Issue by danieltvela** [thoughtbot/Runes#100]
In Sources/Runes/Optional/Optional+Alternative.swift:14 an @autclosure block is passed as an argument. This is forbidden in Swift 5.

From [Swift 5 release notes]( https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes/swift_5_release_notes_for_xcode_10_2):

> In Swift 5 mode, @autoclosure parameters can no longer be forwarded to @autoclosure arguments in another function call. Instead, you must explicitly call the function value with parentheses: (); the call itself is wrapped inside an implicit closure, guaranteeing the same behavior as in Swift 4 mode. (SR-5719) (37321597)

Is there any solution for this?

**Comment by gfontenot** [comment]
It sounds like the solution is to change that line to `return lhs.or(rhs())`, which I'm OK with. Feel like submitting a PR to fix it?

**Comment by gfontenot** [comment]
Also, is this causing a compiler error for Swift 5?

**Comment by danieltvela** [comment]
> It sounds like the solution is to change that line to `return lhs.or(rhs())`, which I'm OK with. Feel like submitting a PR to fix it?

Ok, I'll do it.

> Also, is this causing a compiler error for Swift 5?

Yes, but only occurs in my CI environment. Compiling locally in my machine doesn't produce any error.

**Comment by gfontenot** [comment]
The fix for this is now available in 4.2.2 (uploading to CocoaPods now)
