### ISSUE TITLE
Remove guards for `flatMap`

### ISSUE THREAD

**Issue by gfontenot** [thoughtbot/Runes#13]
Looks like Apple fixed the automatic coercion of `T -> U` into `T -> U?` that was causing us issues with `flatMap`. Since the compiler no longer allows this, we don't need to guard against it manually.

**Comment by perezpaya** [comment]
I'm having an issue that may be related to this
/pods/Runes/Source/Array.swift:79:16: '[T -> U]' does not have a member named 'flatMap'
Having this error alongside all the Pods-Runes install.

Thanks!

**Comment by gfontenot** [comment]
Your error is probably related to #16, not this. You need to make sure that if you're using Runes 1.2+ you're up to date with the most recent beta.

**Comment by perezpaya** [comment]
I'm using Runes through Argo, so I think I'll have to remove Argo until they update this :/

**Comment by gfontenot** [comment]
Same deal with Argo (We maintain both). If you're using the Swift 1.2 releases, we're expecting that you're up to date with the betas. If you use Swift 1.2 Beta 3, you won't have this issue. If you need Swift 1.1 support, you need to be using the 1.1.x release of Runes with the 0.3.x release of Argo.

**Comment by perezpaya** [comment]
Thank you so much @gfontenot
