### ISSUE TITLE
Runes 1.2.2 failed to compile

### ISSUE THREAD

**Issue by Nonouf** [thoughtbot/Runes#28]
I just updated my Pods of Argo (0.4.3) and it installed the last version of Runes (1.2.2) in the same time, but Runes doesn't compile due to errors in Optional.swift and Array.swift. Apprently, the method flatMap doesn't exist.

![screen shot 2015-04-16 at 11 29 43](https://cloud.githubusercontent.com/assets/2992866/7179095/5f1f26b4-e42c-11e4-9fe0-fd45a6b6b269.png)

**Comment by gfontenot** [comment]
Are you in Xcode 6.3? `flatMap` was introduced to the standard library in Swift 1.2, which wasn't shipped till Xcode 6.3.

**Comment by Nonouf** [comment]
Ha no, still in 6.2 and Swift 1.1. What version of Argo and Runes are compatible with Xcode 6.2 ?

**Comment by gfontenot** [comment]
Argo 0.3.x and Runes 1.1.x are compatible with Swift 1.1. Anything past that is assuming Swift 1.2.

Closing this now, but feel free to reopen or file another issue if you run into anything else.
