### ISSUE TITLE
Add flipped fmap operator definition?

### ISSUE THREAD

**Issue by jakecraige** [thoughtbot/Runes#35]
Today I wanted to change this code to use operators:

``` swift
// initial code
return index.map { $0 - 1 }.flatMap { viewControllerAtIndex($0) }

// what I thought would work
return return index <^> { $0 - 1 } >>- { self.viewControllerAtIndex($0) }
```

Turns out the second way gives you `Binary operator '<^>' cannot be applied to operands of type 'Int?' and 'Int -> Int'` because the arguments are backwards for `<^>`. 

You'd have to do something like this to get the same same result:

``` swift
return { self.viewControllerAtIndex($0) } -<< { $0 - 1 } <^> index
```

I'd like to propose adding the type signature for the first way I thought would work (last part of first code example). A similar thing was proposed for Haskell [here](https://ghc.haskell.org/trac/ghc/ticket/8587) but I'm unsure what the current status is. 

Implementing this in Runes would look like adding this method:

``` swift
public func <^><T, U>(a: T?, @noescape f: T -> U) -> U? {
    return a.map(f)
}
```

I believe it would be backwards compatible since the type is flipped so it wouldn't conflict with anyone using it the current way.

I'm not super familiar with Haskell so perhaps this is the way it's done and I need to get used to it, I figured I'd propose this idea to get some discussion around it and hear others thoughts.

**Comment by alskipp** [comment]
It might not be exactly how you'd like to express it, but the following should work:

``` swift
return { $0 - 1 } <^> index >>- { viewControllerAtIndex($0) }
```

**Comment by gfontenot** [comment]
I don't think we're going to be adding this. Closing.
