### ISSUE TITLE
Xcode 7 beta 3 / swift-2.0 Array.swift issue

### ISSUE THREAD

**Issue by toineheuvelmans** [thoughtbot/Runes#39]
As of Xcode beta 3, Runes (swift-2.0) cannot compile, because 'T' has been renamed to 'Element' (as the compiler says in Array.swift)

**Comment by ikesyo** [comment]
You should see #38.

**Comment by gfontenot** [comment]
This should be fixed now. Feel free to re-open if it's still an issue for you.
