### ISSUE TITLE
Incompatible library version: XXX requires version 2.0.0 or later, but Runes provides version 1.0.0

### ISSUE THREAD

**Issue by d6u** [thoughtbot/Runes#43]
I was trying to run my iOS app on my iPhone. Project compiled nicely. But when app starts, XCode console showed:

```
dyld: Library not loaded: @rpath/Runes.framework/Runes
  Referenced from: /private/var/mobile/Containers/Bundle/Application/CC8759F5-A501-400C-93A8-DCEE3BFE4770/XXX.app/XXX
  Reason: Incompatible library version: XXX requires version 2.0.0 or later, but Runes provides version 1.0.0
```

I use Cocoapods and my Podfile looks like:

```
platform :ios, '8.0'
use_frameworks!

pod 'SnapKit', '~> 0.12.0'
pod 'Alamofire', '~> 1.2'
pod 'SwiftTask', '~> 3.3'
pod 'Argo'
pod 'Async', :git => 'https://github.com/duemunk/Async.git', :commit => '9e64046b767fe11010891f5b7fe2aed613a6ee55'
pod 'TapLabel', '0.0.3'
pod 'RealmSwift'
pod 'Kingfisher', '~> 1.4'
```

What should I do? Everything works fine on simulators.

**Comment by gfontenot** [comment]
My initial bet is that this is a CocoaPods problem. The only lib listed that uses Runes is Argo, but we're using a super permissive version constraint there. Have you asked them?

**Comment by d6u** [comment]
Sorry, that was indeed a [cocoapods issue](https://github.com/CocoaPods/CocoaPods/issues/3903). Closing.

**Comment by gfontenot** [comment]
No worries, glad it's not on our end. Thanks for the report!
