### ISSUE TITLE
Audit code for possible annotations

### ISSUE THREAD

**Issue by gfontenot** [thoughtbot/Runes#59]
We added `@noescape` to `<^>` for arrays in #58, but I suspect that we can do more of that. We should audit the existing code and add `@noescape` annotations wherever possible. We should also look into using `rethrows` where we can.

**Comment by sgoodwin** [comment]
`@noescape` is by default now, so instead there are some places that need to be marked as `@escape`.

**Comment by ikesyo** [comment]
Not `@escape` but `@escaping`.
