### ISSUE TITLE
minor enhancement

### ISSUE THREAD

**Issue by forforester** [thoughtbot/Runes#96]
Argo/Sources/Argo/Types/JSON.swift:89: '.flatMap { .success(.some($0)) }' seems to be the same as '.map { .some($0) }'.
Also, the documentation doesn't reflect the removal of '<|', '<|?' operators.
Thanks

**Comment by gfontenot** [comment]
Did you mean to open this against [thoughtbot/Argo](https://github.com/thoughtbot/Argo)?

**Comment by serhiybutz** [comment]
yep, sorry
