### ISSUE TITLE
Suggestion to add default implementation of operators for functions

### ISSUE THREAD

**Issue by ksoftllc** [thoughtbot/Runes#97]
This library is great. Thank you for putting it together.

I'd like to suggest adding some default implementations for functions themselves. I'd be willing to contribute these 4 operators that I see in other languages (F# for example, https://theburningmonk.com/2011/09/fsharp-pipe-forward-and-pipe-backward/):

```
<< func compose backward   f << g          = g(f)   result is a new function
>> func compose forward       f >> g.         = f(g)  result is a new function
<| backward pipe                      f <| g <| x    = f(g(x))   output is the application of both functions to x
|> forward pipe.                         x |> f |> g    = g(f(x))  output is the application of both functions to x 
```
Please tell me if you are interested.

**Comment by gfontenot** [comment]
I've gone back and forth on adding these or not. Ultimately, I thought it was better to keep this scoped to monadic operations and to use a different library for composition. The main reason for that is that Swift handles custom operators _really_ poorly when conflicts arise. So limiting the number of operators defined in a single module feels pretty important.

I actually created [gfontenot/Mozart](https://github.com/gfontenot/Mozart) to handle the composition stuff a while back, but then never really talked about it or promoted it. I'm using it as a test dependency for Runes, but that's about it.

**Comment by ksoftllc** [comment]
Thanks for responding and for pointing me towards Mozart.
